protobot:
  joint_trajectory_controller:
    type: "effort_controllers/JointTrajectoryController"
    joints:
      - base_link_link_01
      - link_01_link_02
      - link_02_link_03
      - link_03_link_04
      - link_04_link_05

    constraints:
      goal_time: 0.5                   # Override default
      stopped_velocity_tolerance: 0.02 # Override default

    gains: # Required because we're controlling an effort interface
      base_link_link_01: {p: 100,  d: 1, i: 1, i_clamp: 1}
      link_01_link_02: {p: 100,  d: 1, i: 1, i_clamp: 1}
      link_02_link_03: {p: 100,  d: 1, i: 1, i_clamp: 1}
      link_03_link_04: {p: 100,  d: 1, i: 1, i_clamp: 1}
      link_04_link_05: {p: 100,  d: 1, i: 1, i_clamp: 1}
